name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r BackEnd/requirements.txt

      - name: Verificar Python
        run: python --version

      - name: Finalizado
        run: echo "Pipeline ejecutado correctamente"
